name: PR Lint and Test

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint

  update-versioning:
    name: Update Versioning
    # if: github.ref == 'refs/heads/main' && github.event_name == 'pull_request'
    needs: lint-and-test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
      uses: actions/checkout@v1
      - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      with:
        extra_plugins: |
          @semantic-release/git
          @semantic-release/exec
          @semantic-release/changelog 
          runs-on: ubuntu-latest